[ESKL-351] refactors SkillsViewModel blocking operations.
Catappult/appcoins-wallet-android pull request #1047
Opened 2024-07-01 10:51 UTC by TiagoAVieira

**What does this PR do?**

   Refactors SkillsViewModel to remove blocking operations. Additionally, it is an attempt to clean some of the logic inside SkillsFragment to make it more manageable. Future refactoring will be necessary, but this is a first step and a noticeable improvement.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] legacy/skills/src/main/java/cm/aptoide/skills/SkillsViewModel.kt

**How should this be manually tested?**

  Test normal eskills flow and referral flow.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/ESKL-351)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-07-04 18:02 UTC, rodolfobcardoso requested changes
Just as a note (no need to change this), usually the .subscribe is done in the viewModel and not in the fragment. The fragment is reconstructed when you rotate the screen or minimize the app, so the rx chains will be created again in this cases.
Since the subscribe is in the fragment, I recommend testing rotating the screen in the middle of the flow to be sure nothing is breaking

2024-07-09 09:02 UTC, TiagoAVieira commented on legacy/skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
> +              }.subscribe()
Got it, will do.

2024-07-09 09:21 UTC, TiagoAVieira commented on legacy/skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
> +              }.subscribe()
Fixed

2024-07-09 09:21 UTC, TiagoAVieira commented on legacy/skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
> +      }.subscribe(),
Added onError

2024-07-09 09:46 UTC, rodolfobcardoso approved these changes

2024-07-09 09:51 UTC, rodolfobcardoso approved these changes

2024-10-14 11:08 UTC, closed without merging