[APPC-4534] New iap payment activity and purchase data
Catappult/appcoins-wallet-android pull request #1112
Opened 2024-08-28 16:14 UTC by ricardo-frango

**What does this PR do?**

   This PR creates the new entry point for the new IAP flow and the PurchaseData model.
   It also disconnects the previous flow.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] PaymentActivityNavigatorFactory.kt
- [ ] PurchaseData.kt
- [ ] MainFragment.kt
- [ ] IabBaseFragment.kt
- [ ] PaymentActivity.kt
- [ ] PaymentActivityNavigator.kt
- [ ] activity_payment.xml
- [ ] iab_graph.xml
- [ ] AndroidManifest.xml

**How should this be manually tested?**

  Try to start the new payment flow. Should see a "Hello" label.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-4534](https://aptoide.atlassian.net/browse/APPC-4534)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-08-30 15:34 UTC, rodolfobcardoso requested changes

2024-08-30 15:34 UTC, rodolfobcardoso commented on app/src/main/java/com/asfoundation/wallet/iab/domain/model/PurchaseData.kt
> +  val chainId: Long,
can be removed

2024-08-30 15:34 UTC, rodolfobcardoso commented on app/src/main/java/com/asfoundation/wallet/iab/domain/model/PurchaseData.kt
> +  val receiverAddress: String?, // shouldn't this be fetched by a request?
can be removed

2024-08-30 15:34 UTC, rodolfobcardoso commented on app/src/main/java/com/asfoundation/wallet/iab/domain/model/PurchaseData.kt
> +  val tokenTransferAmount: BigDecimal?, // shouldn't this be fetched by a request?
can be removed

2024-09-03 15:09 UTC, gustavoaptoide approved these changes

2024-09-17 10:11 UTC, merged