[APPC-4001] Fix hidden get button on small devices
Catappult/appcoins-wallet-android pull request #1113
Opened 2024-08-29 09:03 UTC by rodolfobcardoso

**What does this PR do?**
Fixes the get button on promotions for small devices.

**Database changed?**
No

**What are the relevant tickets?**
https://aptoide.atlassian.net/browse/APPC-4001

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-09-05 09:21 UTC, ricardo-frango requested changes

2024-09-05 09:21 UTC, ricardo-frango commented on ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/ActivePromoCodeComposable.kt
> +              cardItem.action,
add params names

2024-09-05 09:21 UTC, ricardo-frango commented on ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/ActivePromoCodeComposable.kt
> +              Modifier,
this param can be removed

2024-09-05 09:21 UTC, ricardo-frango commented on ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt
> +                cardItem.action,
add names to arguments

2024-09-05 09:21 UTC, ricardo-frango commented on ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt
> +                Modifier,
this param can be removed

2024-09-05 09:21 UTC, ricardo-frango commented on ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt
> +                cardItem.action,
add names to params

2024-09-05 09:21 UTC, ricardo-frango commented on ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt
> +      action.invoke()
remove the invoke. leave just "action()"

2024-09-05 09:24 UTC, ricardo-frango approved these changes

2024-09-11 12:49 UTC, gustavoaptoide approved these changes

2024-09-11 12:49 UTC, merged