[APPC-4532] IAP add OSP parser
Catappult/appcoins-wallet-android pull request #1114
Opened 2024-08-29 15:08 UTC by ricardo-frango

**What does this PR do?**

   This PR adds the parser for the new IAP flow.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] IAPModule.kt
- [ ] PurchaseData.kt
- [ ] MainFragment.kt
- [ ] MissingDataParseException.kt
- [ ] PurchaseUriParameters.kt
- [ ] UriParser.kt
- [ ] PaymentActivity.kt
- [ ] PaymentActivityNavigator.kt
- [ ] iab_graph.xml

**How should this be manually tested?**

  You can test by checking the purchaseData object in the MainFragment.kt

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-4532](https://aptoide.atlassian.net/browse/APPC-4532)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-08-30 16:07 UTC, rodolfobcardoso requested changes

2024-08-30 16:07 UTC, rodolfobcardoso commented on app/src/main/java/com/asfoundation/wallet/iab/parser/osp/OSPUriParserImpl.kt
> +    val amount = currency?.takeIf { it.equals(APPC, true) }
can be removed

2024-08-31 17:58 UTC, mahdishirzad313 commented on app/src/main/res/navigation/iab_graph.xml
> +        android:defaultValue="@null"
mahdishirzad313

2024-09-03 16:16 UTC, gustavoaptoide approved these changes

2024-09-17 10:14 UTC, merged