New String - Bonus in bank transfer
Catappult/appcoins-wallet-android pull request #1211
Opened 2024-11-25 12:11 UTC by carlosgarridoaptoide

**What does this PR do?**

   A few sentences describing the overall goals of the pull request's commits.

   Explain any technical decisions that were made and why (when it makes sense).

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [ ] Foo.java
- [ ] Foo.kt

**How should this be manually tested?**

  Flow on how to test this.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-XXXX)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-11-26 11:41 UTC, carlosgarridoaptoide commented on ui/common/src/main/res/external_strings/values/perks.po
> +msgid "Get {0}% extra bonus in all top-ups made with Easy Bank Transfer."
I've amended the capitalisation to match API.

2024-11-29 18:26 UTC, TiagoAVieira requested changes

2024-12-03 11:30 UTC, TiagoAVieira approved these changes

2024-12-03 11:34 UTC, inesgoldschmidt approved these changes

2025-01-29 14:30 UTC, merged