[ESKL-23] - Fix no network crash.
Catappult/appcoins-wallet-android pull request #122
Opened 2021-05-21 15:45 UTC by FredericoSantinho

**What does this PR do?**

   A few sentences describing the overall goals of the pull request's commits.

   Explain any technical decisions that were made and why (when it makes sense).

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [ ] Foo.java
- [ ] Foo.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [MOB-XXXX](https://aptoide.atlassian.net/browse/MOB-<Jira ticket number>)

**What are the relevant tickets?**

  Tickets related to this pull-request: [MOB-XXXX](https://aptoide.atlassian.net/browse/MOB-<Jira ticket number>)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new libs, new keys, etc.)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2021-06-30 17:43 UTC, Trinkes approved these changes

2021-07-26 14:53 UTC, franciscoaleixo commented on skills/src/main/res/values/strings.xml
> +  <string name="connectoin_error_body">It seems your\'re not connected to the Internet. Check your connection and try again!</string>
typo in "connectoin"

2021-07-26 14:57 UTC, franciscoaleixo requested changes

2021-07-26 14:57 UTC, franciscoaleixo commented on skills/src/main/res/drawable/ic_topup_error.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
This file doesn't seem like it's being used

2021-07-26 15:10 UTC, merged