[WAL-78] ABTest: Balance vs My Wallet
Catappult/appcoins-wallet-android pull request #18
Opened 2020-12-11 17:35 UTC by JDSM01

**What does this PR do?**

   Adds base integration of Ab test
   Adds the Balance vs My Wallet Ab test

**Database changed?**

No

**Where should the reviewer start?**

ABTestCenterRepository.kt

**How should this be manually tested?**

If you are in the My Wallets groups check if the bottom navigation 4th item shows up as Wallets (current string while the final one is not created).
If not check the Rakam logs and check if the group that is being sent is Balance

**What are the relevant tickets?**

https://aptoide.atlassian.net/browse/WAL-78

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2020-12-23 12:35 UTC, pedro-mgb requested changes
The toolbar title in Balance Screen needs to be changed according to the experiment (Balance or MyWallets).

2020-12-23 13:56 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/abtesting/ABTestInteractor.kt
> +  }
Yes. We might need them if we want to test the use case I told you about

2020-12-23 14:29 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/abtesting/RoomExperimentPersistence.kt
> +        .subscribeOn(ioScheduler)
No :(. I would prefer it to

2020-12-28 10:53 UTC, pedro-mgb approved these changes

2020-12-28 10:53 UTC, merged