[task/APPC-3551] Gradle convention plugins and version catalog
Catappult/appcoins-wallet-android pull request #491
Opened 2023-03-01 17:27 UTC by danfbfern

**What does this PR do?**

   refactors gradle integration with convention plugins and version catalog to improve dependency reusability

**Database changed?**

   No

**Where should the reviewer start?**

- build.gradle.kts (:app)
- libs.verions.toml
- convention-plugins module

**What are the relevant tickets?**

 https://aptoide.atlassian.net/browse/APPC-3551

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2023-03-09 10:35 UTC, giovanni-aptoide requested changes

2023-03-09 10:35 UTC, giovanni-aptoide commented on settings.gradle.kts
> +println("Modules:\n\t- ${modules.sortedBy { it }.joinToString("\n\t- ") { it }}")
should these prints be released?

2023-03-09 16:40 UTC, giovanni-aptoide approved these changes

2023-03-10 16:48 UTC, rodolfobcardoso approved these changes

2023-03-10 18:51 UTC, merged