[APPC-2222] MyAppcoins and lang parameter
Catappult/appcoins-wallet-android pull request #52
Opened 2021-02-08 14:32 UTC by pedro-mgb

**What does this PR do?**

   Adds "lang" parameter to myappcoins page (redeem codes), to show page in language used by wallet, and not the one used by browser.
   Adds notes to other pages that will be moved to myappcoins, to remeber to add lang parameter to these

**Database changed?**

   No

**Where should the reviewer start?**

- SettingsFragment.kt

**How should this be manually tested?**

  Change the default language of the browser, to be different than the one used in the wallet app.
  Open wallet app -> Go to settings -> Redeem -> The myappcoins page should be displayed in the language used in wallet (if translations are available), not the one used by the browser

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-2222](https://aptoide.atlassian.net/browse/APPC-2222)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new libs, new keys, etc.)
   Answer: No.

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2021-02-10 15:26 UTC, JDSM01 requested changes
Approved, but there's a mismatch of codes, at least for Chinese because the webpage recognize Chinese as ch, but on the android side the Chinese language is considered zh.

2021-02-26 14:53 UTC, nenehulc commented
Ij

2021-02-26 15:34 UTC, nenehulc requested changes
No

2021-02-28 23:34 UTC, nenehulc approved these changes
Listo

2021-03-03 18:00 UTC, merged