Feature/transactions details wallet v3
Catappult/appcoins-wallet-android pull request #567
Opened 2023-05-10 17:45 UTC by giovanni-aptoide

**What does this PR do?**

   A few sentences describing the overall goals of the pull request's commits.

   Explain any technical decisions that were made and why (when it makes sense).

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [ ] Foo.java
- [ ] Foo.kt

**How should this be manually tested?**

  Flow on how to test this.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-XXXX)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2023-05-11 11:21 UTC, rodolfobcardoso requested changes

2023-05-11 11:21 UTC, rodolfobcardoso commented on ui/common/src/main/res/values/strings.xml
> +  <string name="transaction_rejected_body">This purchase has been rejected.\nFor more information contact support.</string>
might be better not to change the strings files manually, as this will likely cause problems on Crowdin

2023-05-11 12:35 UTC, giovanni-aptoide commented on app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
> +                description = description ?: app,
I agree, it probably will be done further

2023-05-11 12:45 UTC, giovanni-aptoide commented on app/src/main/java/com/asfoundation/wallet/transactions/TransactionModel.kt
> +const val TRANSACTION_BASE_URL = "https://appcexplorer.io/transaction/"
thank you, done

2023-05-22 11:12 UTC, rodolfobcardoso requested changes

2023-05-22 11:12 UTC, rodolfobcardoso commented on app/src/main/java/com/asfoundation/wallet/repository/TransactionsHistoryPagingSource.kt
> +  val backend: TransactionsApi,
not sure if this is intentional, but this class could have the parameters injected in the constructor: 
class TransactionsHistoryPagingSource @Inject constructor(...)
Was it made this way to have a different PagingSource instance for each wallet?

2023-05-22 13:30 UTC, rodolfobcardoso approved these changes

2023-05-23 09:01 UTC, merged