[APPC-3811] IAP Payment Flow Optimization Part 1
Catappult/appcoins-wallet-android pull request #643
Opened 2023-07-31 12:31 UTC by Roguezilla

**What does this PR do?**
Optimize web call usage in the payment flow for faster loading times.

**Database changed?**
No

**How should this be manually tested?**
Make any payment (and check if the bonus is correct).
Make an Onboarding payment and check if the bonus is correct.
Top-up and check if the bonus is correct.

**What are the relevant tickets?**
https://aptoide.atlassian.net/browse/APPC-3811

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2023-07-31 12:31 UTC, catappult-codebuilder-dev2 commented
Can one of the admins verify this patch?

2023-08-02 10:22 UTC, rodolfobcardoso requested changes
I suggested 2 small changes, everything else looks good to me 👍

2023-08-02 10:22 UTC, rodolfobcardoso commented on app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationInteractor.kt
> +          conversionService.getAppcToLocalFiat(appcBonusValue.amount.toString(), 18).flatMap { fiatValue ->
Instead of using a flatMap that returns a new Single, you can have a rxJava map. This way you can use the same Single by mapping only it's content

2023-08-02 10:22 UTC, rodolfobcardoso commented on app/src/test/java/com/asfoundation/wallet/util/OneStepWatchedTransactionParserTest.kt
> +    //test.assertValue { transactionBuilder -> transactionBuilder.contractAddress() == contractAddress }
please delete this commented lines if not needed anymore.

2023-08-03 08:53 UTC, rodolfobcardoso approved these changes

2023-08-03 15:46 UTC, merged