[APPC-2243] Evouchers: Purchase flow
Catappult/appcoins-wallet-android pull request #66
Opened 2021-02-19 17:22 UTC by JDSM01

**What does this PR do?**

Implements the new design of the purchase flow while keeping the current one on the iap

**Database changed?**

   No

**Where should the reviewer start?**

IabActivity.kt
AdyenPaymentPresenter.kt

**How should this be manually tested?**

On IabActivity you have a function that returns if should use bottom sheet or not, change that function to return the test case. Also change other conditions that may depend on the type of transaction since if the transaction is VOUCHER no payment methods will be returned. 

**What are the relevant tickets?**

https://aptoide.atlassian.net/browse/APPC-2243

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2021-02-22 16:15 UTC, franciscoaleixo requested changes

2021-02-22 19:12 UTC, franciscoaleixo commented
When testing IAB with bottom sheet and credit card, the success screen is the voucher one although it shouldn't.

2021-03-08 10:01 UTC, JoaoRaimundo requested changes

2021-03-09 16:59 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
> +          val paymentData = data.paymentData
I believe we are. Not only in space and readability and we avoid accessing data. several times

2021-03-09 17:00 UTC, JDSM01 commented on app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
> +    val paymentData = data.paymentData
Same as before

2021-03-11 15:22 UTC, merged