New String - Challenge Reward Dated
Catappult/appcoins-wallet-android pull request #745
Opened 2023-10-03 11:26 UTC by carlosgarridoaptoide

**What does this PR do?**

   A few sentences describing the overall goals of the pull request's commits.

   Explain any technical decisions that were made and why (when it makes sense).

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [ ] Foo.java
- [ ] Foo.kt

**How should this be manually tested?**

  Flow on how to test this.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-XXXX)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2023-10-03 11:30 UTC, AngeloMendonca approved these changes

2023-10-03 13:10 UTC, giovanni-aptoide approved these changes

2023-10-04 13:27 UTC, AngeloMendonca requested changes

2023-10-04 13:27 UTC, AngeloMendonca commented on ui/common/src/main/res/values/strings.xml
> +  <string name="transaction_type_challenge_reward_reverted_date">The Challenge Reward of %s has been reverted.</string>
Wrong String added. Correct one: `This Bonus has been reverted. For more information contact support`

2023-10-04 13:28 UTC, giovanni-aptoide approved these changes

2023-10-09 09:23 UTC, AngeloMendonca commented
Sorry for the misinformation @carlosgarridoaptoide , this string is not needed

2023-10-09 09:23 UTC, closed without merging