Feat[APPC-4095]  Analytics Identify if users have GamesHub installed
Catappult/appcoins-wallet-android pull request #866
Opened 2024-01-04 15:55 UTC by gustavoaptoide

**What does this PR do?**

  include super properties inside Analytics to send in every analytics if user have GH installed and correct OEMID

**Database changed?**

   No

**How should this be manually tested?**

 Clean the wallet cache and open wallet with GH install or not and see the analytics parameter gh_oemid

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-4095](https://aptoide.atlassian.net/browse/APPC-4095)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-01-04 18:19 UTC, badasserry requested changes
..

2024-01-04 18:19 UTC, badasserry commented on core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/OemIdPreferencesDataSource.kt
> -  fun getCurrentOemId() = sharedPreferences.getString(CURRENT_OEMID, "") ?: ""
This is to get the content of wallet to not be seen by user/miner whilst it is moved out, correct? Or am I wrong?

2024-01-05 14:17 UTC, rodolfobcardoso requested changes

2024-01-08 16:13 UTC, rodolfobcardoso approved these changes

2024-01-08 17:38 UTC, merged