New Strings - Delete wallet confirmation
Catappult/appcoins-wallet-android pull request #887
Opened 2024-01-17 11:13 UTC by carlosgarridoaptoide

**What does this PR do?**

   A few sentences describing the overall goals of the pull request's commits.

   Explain any technical decisions that were made and why (when it makes sense).

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [ ] Foo.java
- [ ] Foo.kt

**How should this be manually tested?**

  Flow on how to test this.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-XXXX)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-01-17 18:34 UTC, rodolfobcardoso commented
run-jenkins-build

2024-01-18 11:02 UTC, giovanni-aptoide requested changes

2024-01-18 11:02 UTC, giovanni-aptoide commented on ui/common/src/main/res/values/strings.xml
> +  <string name="remove_wallet_extra_confirmation_body">Remember that, without a backup, you'll lose your funds and bonus level</string>
@carlosgarridoaptoide special characters like  ' needs a \ before.

2024-01-18 18:24 UTC, giovanni-aptoide approved these changes

2024-01-18 18:25 UTC, merged