[feature/APPC-2431] Refactor Home
Catappult/appcoins-wallet-android pull request #96
Opened 2021-04-27 15:57 UTC by franciscoaleixo

**What does this PR do?**

   This PR refactors home according to the new visuals and improves several flows, including:
   - Home now doesn't refresh the whole screen when we go back to it. It does refresh the data, but this is done on background silently and then only the changes are reflected on screen (no more loading all the time).
   -  Wallet creation is now handled as it should. When we created a wallet before, we still emitted 0 transactions and 0 balance in some cases before updating it, now that should be fixed.
   - A lot of cleanup, simplifying and better chain parallelization, which should mean better performance and loading times in Home.

Additionally, the recyclerview was completely replaced, now using Epoxy and also using ViewBinding to replace findViewById. I'm also using MotionLayout for Home (I did not see any other way to make animations work). I also had to bump kotlin version and gradle version as a result of these changes. Finally, there's still room for improvement here, and I hope to finish the rest of the refactor when we adapt this into the bottom navigation (especially the view part).

At the time of writing, I couldn't yet make dissappearing animations work for the notifications cards. I'm still seeing if I can make something work, but this is not blocking.

**Database changed?**

   No

**Where should the reviewer start?**

Probably TransactionsActivity or TransactionsViewModel. For heavily diffed files (like TransactionsActivity or TransactionsViewModel), I don't recommend focusing on the diff, but rather just looking directly at the new code and then validating the changes through testing, since they were a lot of changes.

**How should this be manually tested?**

  Validate the whole home if everything is working as it should (apart from the new design), but also there were some changes outside of this (like in wallet creation), so ideally we should run regression tests. Also test in landscape.

**What are the relevant tickets?**

  [APPC-2431](https://aptoide.atlassian.net/browse/APPC-2431)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2021-05-06 15:08 UTC, JoaoRaimundo requested changes

2021-05-06 15:11 UTC, umutk1107 commented
Umut-karacan-48@hotmail.com

2021-05-06 15:13 UTC, umutk1107 approved these changes

2021-05-07 09:24 UTC, franciscoaleixo commented on app/src/main/res/layout/layout_collapsing_app_bar.xml
> +    android:layout_height="180dp"
The file was actually not being used anymore

2021-05-10 06:20 UTC, merged