[APPC-4209] Integrate MiPay
Catappult/appcoins-wallet-android pull request #963
Opened 2024-04-16 08:33 UTC by giovanni-aptoide

**What does this PR do?**

   Integrate new payment method: mipay

**Database changed?**

   No

**How should this be manually tested?**

  with a gamed injected with xiaomi oemid, try to make a payment in one of the available countries for mipay, like Russia.
  On IAP or onboarding you should have just 1 option to make payments

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-4209](https://aptoide.atlassian.net/browse/APPC-4209)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-05-22 10:34 UTC, rodolfobcardoso requested changes

2024-05-22 10:34 UTC, rodolfobcardoso commented on app/src/main/java/com/asfoundation/wallet/billing/mipay/MiPayViewModel.kt
> +        analytics.sendPaymentErrorEvent(
On user cancelation we shouldn't send an error event, only if there was an actual error with the payment. On user cancel it should go back to the payment methods

2024-05-22 10:34 UTC, rodolfobcardoso commented on app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/mipay/OnboardingMiPayFragment.kt
> +  fun showError(message: Int?) {
There should be an error event

2024-05-22 17:06 UTC, giovanni-aptoide commented on app/src/main/java/com/asfoundation/wallet/billing/CreditsRemoteRepository.java
> +        orderReference, referrerUrl, productToken, signature);
removed

2024-05-22 17:06 UTC, giovanni-aptoide commented on app/src/main/java/com/asfoundation/wallet/billing/mipay/MiPayFragment.kt
> +        RedirectComponent.getReturnUrl(requireContext())
created RedirectUtils

2024-05-22 17:07 UTC, giovanni-aptoide commented on app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/mipay/OnboardingMiPayFragment.kt
> +  fun showError(message: Int?) {
done

2024-05-27 14:05 UTC, rodolfobcardoso approved these changes

2024-05-27 14:17 UTC, rodolfobcardoso approved these changes

2024-05-27 16:06 UTC, merged