DES-478 - New Strings - Transfer funds
Catappult/appcoins-wallet-android pull request #975
Opened 2024-05-03 13:46 UTC by carlosgarridoaptoide

**What does this PR do?**

   A few sentences describing the overall goals of the pull request's commits.

   Explain any technical decisions that were made and why (when it makes sense).

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [ ] Foo.java
- [ ] Foo.kt

**How should this be manually tested?**

  Flow on how to test this.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-XXXX)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-05-06 11:39 UTC, inesgoldschmidt reviewed
Looks great!

2024-05-08 12:08 UTC, rodolfobcardoso requested changes

2024-05-08 12:08 UTC, rodolfobcardoso commented on ui/common/src/main/res/values/strings.xml
> +  <string name="p2p_send_title">Receive</string>
duplicated key

2024-05-08 14:58 UTC, carlosgarridoaptoide commented on ui/common/src/main/res/values/strings.xml
> +  <string name="p2p_send_title">Receive</string>
Solved

2024-05-08 17:36 UTC, rodolfobcardoso approved these changes

2024-05-08 17:36 UTC, merged