Typos
Catappult/appcoins-wallet-android pull request #987
Opened 2024-05-13 12:00 UTC by carlosgarridoaptoide

**What does this PR do?**

   A few sentences describing the overall goals of the pull request's commits.

   Explain any technical decisions that were made and why (when it makes sense).

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [ ] Foo.java
- [ ] Foo.kt

**How should this be manually tested?**

  Flow on how to test this.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-XXXX)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2024-05-13 12:01 UTC, inesgoldschmidt requested changes

2024-05-13 12:01 UTC, inesgoldschmidt commented on ui/common/src/main/res/values/strings.xml
> +  <string name="transaction_details_header">Transaction Dacetails</string>
Transaction Details

2024-05-15 08:51 UTC, giovanni-aptoide approved these changes

2024-05-15 08:52 UTC, giovanni-aptoide approved these changes

2024-05-15 09:19 UTC, inesgoldschmidt approved these changes

2024-05-15 10:02 UTC, merged